# Generated by Django 5.2.8 on 2025-12-12 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashadmin', '0002_projet_taux'),
    ]

    operations = [
        migrations.AddField(
            model_name='projet',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='projets/images/'),
        ),
    ]
