# Generated by Django 5.2.8 on 2025-12-14 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashadmin', '0006_member_partenariat'),
    ]

    operations = [
        migrations.RenameField(
            model_name='benevole',
            old_name='organisation',
            new_name='competences',
        ),
        migrations.AddField(
            model_name='benevole',
            name='cv',
            field=models.FileField(blank=True, null=True, upload_to='bénévoles/'),
        ),
    ]
