# Generated by Django 5.2.8 on 2025-12-12 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashadmin', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='projet',
            name='taux',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
    ]
