# Generated by Django 5.2.8 on 2025-12-13 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashadmin', '0003_projet_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ressource',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='ressources/images/'),
        ),
        migrations.AlterField(
            model_name='ressource',
            name='url',
            field=models.FileField(blank=True, null=True, upload_to='ressources/fichiers/'),
        ),
    ]
