# Generated by Django 5.2.8 on 2025-12-13 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashadmin', '0004_alter_ressource_image_alter_ressource_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='ressource',
            name='statut',
            field=models.CharField(blank=True, choices=[('publier', 'Publier'), ('non_publier', 'Non publier')], max_length=80, null=True),
        ),
    ]
