# Generated by Django 5.2.8 on 2025-12-13 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashadmin', '0005_ressource_statut'),
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('poste', models.CharField(max_length=150)),
                ('photo', models.ImageField(upload_to='team/')),
                ('description', models.TextField()),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Partenariat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_partenariat', models.CharField(choices=[('financier', 'Partenariat financier'), ('technique', 'Partenariat technique'), ('institutionnel', 'Partenariat institutionnel'), ('benevole', 'Bénévolat / Engagement personnel'), ('autre', 'Autre')], max_length=30)),
                ('nom_organisation', models.CharField(blank=True, help_text="Nom de l'organisation ou institution", max_length=150, null=True)),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('telephone', models.CharField(max_length=30)),
                ('pays', models.CharField(blank=True, max_length=100, null=True)),
                ('ville', models.CharField(blank=True, max_length=100, null=True)),
                ('objet', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('document', models.FileField(blank=True, null=True, upload_to='partenariats/')),
                ('statut', models.CharField(choices=[('nouvelle', 'Nouvelle'), ('en_cours', 'En cours de traitement'), ('acceptee', 'Acceptée'), ('refusee', 'Refusée')], default='nouvelle', max_length=20)),
                ('date_soumission', models.DateTimeField(auto_now_add=True)),
                ('date_traitement', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Demande de partenariat',
                'verbose_name_plural': 'Demandes de partenariat',
                'ordering': ['-date_soumission'],
            },
        ),
    ]
