# Generated by Django 5.2.8 on 2025-12-14 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashadmin', '0007_rename_organisation_benevole_competences_benevole_cv'),
    ]

    operations = [
        migrations.AddField(
            model_name='benevole',
            name='pays',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='benevole',
            name='ville',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
